<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Gamme extends \AppBundle\Entity\Gamme implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'reglecalcul', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'finitionexterieur', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'typeisolant', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'couverture', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'qualitehuisserie', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'idgamme'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'reglecalcul', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'finitionexterieur', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'typeisolant', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'couverture', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'qualitehuisserie', '' . "\0" . 'AppBundle\\Entity\\Gamme' . "\0" . 'idgamme'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Gamme $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setReglecalcul($reglecalcul)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReglecalcul', [$reglecalcul]);

        return parent::setReglecalcul($reglecalcul);
    }

    /**
     * {@inheritDoc}
     */
    public function getReglecalcul()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReglecalcul', []);

        return parent::getReglecalcul();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinitionexterieur($finitionexterieur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinitionexterieur', [$finitionexterieur]);

        return parent::setFinitionexterieur($finitionexterieur);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinitionexterieur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinitionexterieur', []);

        return parent::getFinitionexterieur();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeisolant($typeisolant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeisolant', [$typeisolant]);

        return parent::setTypeisolant($typeisolant);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeisolant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeisolant', []);

        return parent::getTypeisolant();
    }

    /**
     * {@inheritDoc}
     */
    public function setCouverture($couverture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCouverture', [$couverture]);

        return parent::setCouverture($couverture);
    }

    /**
     * {@inheritDoc}
     */
    public function getCouverture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCouverture', []);

        return parent::getCouverture();
    }

    /**
     * {@inheritDoc}
     */
    public function setQualitehuisserie($qualitehuisserie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQualitehuisserie', [$qualitehuisserie]);

        return parent::setQualitehuisserie($qualitehuisserie);
    }

    /**
     * {@inheritDoc}
     */
    public function getQualitehuisserie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualitehuisserie', []);

        return parent::getQualitehuisserie();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdgamme()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdgamme();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdgamme', []);

        return parent::getIdgamme();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
