<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Module extends \AppBundle\Entity\Module implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'unite', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'nature', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'epaisseur', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'longueur', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'hauteur', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'angleentrant', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'anglesortant', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'idmodule', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'gamme'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'unite', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'nature', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'epaisseur', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'longueur', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'hauteur', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'angleentrant', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'anglesortant', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'idmodule', '' . "\0" . 'AppBundle\\Entity\\Module' . "\0" . 'gamme'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Module $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setUnite($unite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnite', [$unite]);

        return parent::setUnite($unite);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnite', []);

        return parent::getUnite();
    }

    /**
     * {@inheritDoc}
     */
    public function setNature($nature)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNature', [$nature]);

        return parent::setNature($nature);
    }

    /**
     * {@inheritDoc}
     */
    public function getNature()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNature', []);

        return parent::getNature();
    }

    /**
     * {@inheritDoc}
     */
    public function setEpaisseur($epaisseur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEpaisseur', [$epaisseur]);

        return parent::setEpaisseur($epaisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function getEpaisseur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEpaisseur', []);

        return parent::getEpaisseur();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongueur($longueur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongueur', [$longueur]);

        return parent::setLongueur($longueur);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongueur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongueur', []);

        return parent::getLongueur();
    }

    /**
     * {@inheritDoc}
     */
    public function setHauteur($hauteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHauteur', [$hauteur]);

        return parent::setHauteur($hauteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getHauteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHauteur', []);

        return parent::getHauteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setAngleentrant($angleentrant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAngleentrant', [$angleentrant]);

        return parent::setAngleentrant($angleentrant);
    }

    /**
     * {@inheritDoc}
     */
    public function getAngleentrant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAngleentrant', []);

        return parent::getAngleentrant();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnglesortant($anglesortant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnglesortant', [$anglesortant]);

        return parent::setAnglesortant($anglesortant);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnglesortant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnglesortant', []);

        return parent::getAnglesortant();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmodule($idmodule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmodule', [$idmodule]);

        return parent::setIdmodule($idmodule);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmodule()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdmodule();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmodule', []);

        return parent::getIdmodule();
    }

    /**
     * {@inheritDoc}
     */
    public function setGamme(\AppBundle\Entity\Gamme $gamme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGamme', [$gamme]);

        return parent::setGamme($gamme);
    }

    /**
     * {@inheritDoc}
     */
    public function getGamme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGamme', []);

        return parent::getGamme();
    }

}
